artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/nlsrikanth7/Cat_and_Dog/raw/main/winequality-red.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation: 
  root_dir: artifacts/data_validation # This will create another folder called data_validation under artifacts folders
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt #create status.txt file under data_validation folder. 

data_transformation:
  root_dir: artifacts/data_transformation # this will create another folder call data_transformation under artifacts folder
  data_path: artifacts/data_ingestion/winequality-red.csv


model_trainer:
  root_dir: artifacts/model_trainer # this will create another folder called model_trainer under artifacts 
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib  # model file will be joblib type, we can also save as pkl (pickel file)

model_evaluation:
  root_dir: artifacts/model_evaluation # this will create another folder called model_trainer under artifacts 
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib 
  metric_file_name: artifacts/model_evaluation/metrics.json
